export const constGraphTitles =  [
    { title: 'RPM', units: 'RPM' },
    { title: 'Air To Fuel', units: '' },
    { title: 'Manifold Air Pressure', units: 'kPa' },
    { title: 'Throttle Position', units: '%' },
    { title: 'Engine Temperature', units: '&deg;C' },
    { title: 'Oil Temperature', units: '&deg;C' },
    { title: 'Fuel Temperature', units: '˚C' },
    { title: 'Intake Air Temperature', units: '&deg;C' },
    { title: 'Oil Pressure', units: 'kPa' },
    { title: 'Barometer', units: 'kPa' },
    { title: 'Injector Pulse Width', units: 'seconds' },
    { title: 'Suspension', units: 'mm' },
    { title: 'Acceleration', units: 'g' },
    { title: 'Roll', units: '&deg;' },
    { title: 'Pitch', units: '&deg;' },
    { title: 'Yaw', units: '&deg;' },
    { title: 'Speed', units: 'km/h' },
    { title: 'Distance', units: 'm' },
    { title: 'Track Map', units: '' }]

