const ACCESS_KEY = 'AKIATH6ROILNBEML3ZA4'
const SECRET_KEY = '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'
const REGION = 'us-west-2'
const BUCKET_NAME = '2020-2021'

module.exports = { ACCESS_KEY, SECRET_KEY, REGION, BUCKET_NAME }